### ISSUE TITLE
can't mutate .feature

### ISSUE THREAD

**Issue by vjcitn** [stemangiola/tidySummarizedExperiment#116]
after
```
library(tidySummarizedExperiment)
library(airway)
data(airway)
library(tidyprint)
```
we have
```
> airway |> mutate(ensg=.feature)
Error in `dplyr_fn()`:
ℹ In argument: `ensg = .feature`.
Caused by error:
! object '.feature' not found
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
`when()` was deprecated in purrr 1.0.0.
ℹ Please use `if` instead.
ℹ The deprecated feature was likely used in the tidySummarizedExperiment package.
  Please report the issue at <https://github.com/stemangiola/tidySummarizedExperiment/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```
I think that used to work.
```
> sessionInfo()
R Under development (unstable) (2025-12-17 r89190)
Platform: aarch64-unknown-linux-gnu
Running under: Ubuntu 24.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/aarch64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/aarch64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats4    stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] tidyprint_0.99.7                airway_1.31.0                  
 [3] ggplot2_4.0.1                   tidyr_1.3.2                    
 [5] dplyr_1.1.4                     tidySummarizedExperiment_1.21.0
 [7] ttservice_0.5.3                 SummarizedExperiment_1.41.0    
 [9] Biobase_2.71.0                  GenomicRanges_1.63.1           
[11] Seqinfo_1.1.0                   IRanges_2.45.0                 
[13] S4Vectors_0.49.0                BiocGenerics_0.57.0            
[15] generics_0.1.4                  MatrixGenerics_1.23.0          
[17] matrixStats_1.5.0              

loaded via a namespace (and not attached):
 [1] utf8_1.2.6          plotly_4.11.0       SparseArray_1.11.10
 [4] stringi_1.8.7       lattice_0.22-7      digest_0.6.39      
 [7] magrittr_2.0.4      grid_4.6.0          RColorBrewer_1.1-3 
[10] fastmap_1.2.0       jsonlite_2.0.0      Matrix_1.7-4       
[13] httr_1.4.7          fansi_1.0.7         purrr_1.2.0        
[16] viridisLite_0.4.2   scales_1.4.0        lazyeval_0.2.2     
[19] abind_1.4-8         cli_3.6.5           crayon_1.5.3       
[22] rlang_1.1.6         XVector_0.51.0      ellipsis_0.3.2     
[25] withr_3.0.2         DelayedArray_0.37.0 S4Arrays_1.11.1    
[28] tools_4.6.0         vctrs_0.6.5         R6_2.6.1           
[31] lifecycle_1.0.4     stringr_1.6.0       htmlwidgets_1.6.4  
[34] pkgconfig_2.0.3     pillar_1.11.1       gtable_0.3.6       
[37] glue_1.8.0          data.table_1.17.8   tibble_3.3.0       
[40] tidyselect_1.2.1    farver_2.1.2        htmltools_0.5.9    
[43] compiler_4.6.0      S7_0.2.1           
```
BTW there are a lot of branches in the main repo.  Can some be dropped?  Non-default branches can be of interest if one wants to see if an incubating or experimental branch avoids a problem.

**Comment by stemangiola** [comment]
Hello @vjcitn, the PR/branch above it should solve this issue. If you try it and you are happy, I will merge.

**Comment by stemangiola** [comment]
> BTW there are a lot of branches in the main repo. Can some be dropped? Non-default branches can be of interest if one wants to see if an incubating or experimental branch avoids a problem.

I cleaned them up, thanks!

**Comment by vjcitn** [comment]
Thanks Stefano.  With that PR I still see
```
Warning message:
`when()` was deprecated in purrr 1.0.0.
ℹ Please use `if` instead.
ℹ The deprecated feature was likely used in the tidySummarizedExperiment package.
  Please report the issue at <https://github.com/stemangiola/tidySummarizedExperiment/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 
```
but your change did repair the problem noted with mutate.

**Comment by stemangiola** [comment]
Amazing. Yes, I had this `when()` business on my to-do list. I'll take care of it. 🙏
